#!/usr/bin/env node
/**
 * Bakes data/*.json into js/data.generated.js as plain globals so the
 * dashboard runs from a `file://` URL with zero build tooling and no
 * dev server required (a local JSON `fetch()` is blocked by browsers
 * under file://, so we inline it as a <script> instead).
 *
 * Run this whenever data/mentions.seed.json or data/social.seed.json
 * change (including after scripts/verify-links.mjs updates linkStatus):
 *
 *   node scripts/build-data.mjs
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

async function main() {
  const mentions = JSON.parse(await readFile(path.join(root, "data", "mentions.seed.json"), "utf-8"));
  const social = JSON.parse(await readFile(path.join(root, "data", "social.seed.json"), "utf-8"));

  const banner = `/* AUTO-GENERATED by scripts/build-data.mjs — do not edit by hand.\n   Source of truth: data/mentions.seed.json and data/social.seed.json. */\n`;
  const out = `${banner}const MENTIONS_SEED = ${JSON.stringify(mentions, null, 2)};\nconst SOCIAL_SEED = ${JSON.stringify(social, null, 2)};\n`;

  await writeFile(path.join(root, "js", "data.generated.js"), out, "utf-8");
  console.log(`Wrote js/data.generated.js (${mentions.length} mentions, ${social.posts.length} social posts).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
